package grcom;

import static org.junit.Assert.assertEquals;

import java.io.File;
import java.util.concurrent.TimeUnit;

import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.support.ui.Select;

public class selfcare {
	final static FirefoxProfile profile = new FirefoxProfile(new File("C:/Users/awafa/AppData/Roaming/Mozilla/Firefox/Profiles"));
	// static WebDriver webDriver = new FirefoxDriver(profile);	
  private WebDriver driver;
  private String baseUrl;
 // private boolean acceptNextAlert = true;
  private StringBuffer verificationErrors = new StringBuffer();

  @Before
  public void setUp() throws Exception {
    driver = new FirefoxDriver();
    baseUrl = "https://gridstaging.globalrescue.com/";
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
  }

  @Test
  public void selfcaree() throws Exception {
   driver.get(baseUrl + "/grcom/signup/signup.xhtml");
    
   driver.findElement(By.xpath("//a[@id='topHeaderLinksForm:j_idt22']/h6")).click();
   Thread.sleep(4000);
   assertTrue(isElementPresent(By.xpath("//a[@id='topHeaderLinksForm:j_idt48']/h5")));
   assertTrue(isElementPresent(By.xpath("//span[@id='topHeaderLinksForm:loginPanel']/div/div[5]/div[2]/a/h5")));
   driver.findElement(By.id("topHeaderLinksForm:j_idt46")).click();
   Thread.sleep(4000);
   assertEquals("User Name cannot be empty", driver.findElement(By.cssSelector("h6.errormessage.margin-zero")).getText());
   assertEquals("Password cannot be empty", driver.findElement(By.xpath("//span[@id='topHeaderLinksForm:loginPanel']/div/div[2]/div[2]/h6")).getText());
   driver.findElement(By.id("topHeaderLinksForm:usernameTxtField")).clear();
   driver.findElement(By.id("topHeaderLinksForm:usernameTxtField")).sendKeys("!@#$%");
   driver.findElement(By.id("topHeaderLinksForm:passwordTxtField")).clear();
   driver.findElement(By.id("topHeaderLinksForm:passwordTxtField")).sendKeys("!@#$%");
   driver.findElement(By.id("topHeaderLinksForm:j_idt46")).click();
   Thread.sleep(4000);
   assertEquals("Invalid User Name or Password", driver.findElement(By.cssSelector("h6.errormessage.margin-zero")).getText());
   driver.findElement(By.id("topHeaderLinksForm:usernameTxtField")).clear();
   driver.findElement(By.id("topHeaderLinksForm:usernameTxtField")).sendKeys("login@test.com");
   driver.findElement(By.id("topHeaderLinksForm:passwordTxtField")).clear();
   driver.findElement(By.id("topHeaderLinksForm:passwordTxtField")).sendKeys("gridtest");
   driver.findElement(By.id("topHeaderLinksForm:j_idt46")).click();
   Thread.sleep(9000);
   System.out.println("Invalid and Empty Login Credentials have been checked!");
   System.out.println("Forgot Password and Create New Account Links have been checked!");
   
   assertEquals("Active Membership", driver.findElement(By.xpath("//div[@id='page-wrapper']/div/div/div/div[2]/div/h2")).getText());
   assertEquals("October 09, 2015", driver.findElement(By.xpath("//div[@id='page-wrapper']/div/div/div/div[2]/div/div/div/h4[2]")).getText());
   assertEquals("October 08, 2018", driver.findElement(By.xpath("//div[@id='page-wrapper']/div/div/div/div[2]/div/div/div/h4[4]")).getText());
   assertEquals("Individual", driver.findElement(By.xpath("//div[@id='page-wrapper']/div/div/div/div[2]/div/div[2]/div/div[2]/h4")).getText());
   assertEquals("Medical Only", driver.findElement(By.xpath("//div[@id='page-wrapper']/div/div/div/div[2]/div/div[2]/div[2]/div[2]/h4")).getText());
   assertEquals("3 years", driver.findElement(By.xpath("//div[@id='page-wrapper']/div/div/div/div[2]/div/div[2]/div[3]/div[2]/h4")).getText());
   assertEquals("45 days", driver.findElement(By.xpath("//div[@id='page-wrapper']/div/div/div/div[2]/div/div[2]/div[4]/div[2]/h4")).getText());
   assertTrue(isElementPresent(By.id("selfCareForm:renewBtn")));
   assertEquals("CHANGE PASSWORD", driver.findElement(By.id("selfCareForm:changePasswordBtn")).getText());
   assertTrue(isElementPresent(By.linkText("Destination Reports")));
   System.out.println("User has successfully logged in!");
   Thread.sleep(5000);
   System.out.println("Membership Title,Start Date,End Date,Type of plan,Coverage,Term, Maximum Days Details have been checked!");
		/*/////ALL LINKS//////
driver.findElement(By.xpath("//span[@id='menu']/li[1]/a")).click();
Thread.sleep(10000);
assertEquals("THE GLOBAL RESCUE ADVANTAGE: OUR PEOPLE", driver.findElement(By.xpath("//div[@id='page-wrapper']/div/div/div/div/h1")).getText());
driver.findElement(By.xpath("//li[@id='outTeamContent']/a/span")).click();
Thread.sleep(5000);
driver.findElement(By.xpath("//div[@id='leadership']/ul/li[14]/h5")).click();
Thread.sleep(5000);
driver.findElement(By.xpath("//div[@id='medicalDirectors']/ul/li[6]/h5")).click();
Thread.sleep(5000);
driver.findElement(By.xpath("//div[@id='johnHopkinsTeam']/ul/li[2]/h5")).click();
Thread.sleep(5000);
assertEquals("Daniel L. Richards – Chief Executive Officer", driver.findElement(By.xpath("//div[@id='leadership']/ul/li/h4/div")).getText());
driver.findElement(By.xpath("//li[@id='ourMissionContent']/a/span")).click();
Thread.sleep(5000);
assertEquals("OUR MISSION", driver.findElement(By.xpath("//div[@id='page-wrapper']/div[2]/div/div/div[2]/div[3]/h2/div")).getText());
driver.findElement(By.xpath("//li[@id='partnersContent']/a/span")).click();
Thread.sleep(5000);
assertEquals("PARTNERS", driver.findElement(By.xpath("//div[@id='page-wrapper']/div[2]/div/div/div[2]/div[5]/h2/div")).getText());
driver.findElement(By.xpath("//li[@id='contactUsContent']/a/span")).click();
Thread.sleep(5000);
assertEquals("CONTACT US", driver.findElement(By.xpath("//div[@id='page-wrapper']/div[2]/div/div/div[2]/div[4]/div/div[2]/h2/div")).getText());

assertEquals("ENROLL NOW", driver.findElement(By.cssSelector("#j_idt76 > a.text-red")).getText());
driver.findElement(By.id("contactUsForm:j_idt108")).click();
Thread.sleep(5000);
assertEquals("First Name cannot be empty", driver.findElement(By.cssSelector("h6.errormessage.margin-zero")).getText());
driver.findElement(By.id("nextQuote")).click();
Thread.sleep(5000);
assertEquals("Last Name cannot be empty", driver.findElement(By.xpath("//div[@id='contactUsEmailForm']/div/div[2]/div[2]/h6")).getText());
assertEquals("Email cannot be empty", driver.findElement(By.xpath("//div[@id='contactUsEmailForm']/div/div[3]/div[2]/h6")).getText());
driver.findElement(By.name("contactUsForm:j_idt82")).clear();
driver.findElement(By.name("contactUsForm:j_idt82")).sendKeys("test");
driver.findElement(By.name("contactUsForm:j_idt86")).clear();
driver.findElement(By.name("contactUsForm:j_idt86")).sendKeys("test");
driver.findElement(By.name("contactUsForm:j_idt90")).clear();
driver.findElement(By.name("contactUsForm:j_idt90")).sendKeys("test@yahoo.com");
driver.findElement(By.id("contactUsForm:mobileNumberInput:mobileNumberInput")).clear();
driver.findElement(By.id("contactUsForm:mobileNumberInput:mobileNumberInput")).sendKeys("(+1)2222");
driver.findElement(By.name("contactUsForm:j_idt100")).click();
new Select(driver.findElement(By.name("contactUsForm:j_idt100"))).selectByVisibleText("During office hours");
driver.findElement(By.name("contactUsForm:j_idt106")).clear();
driver.findElement(By.name("contactUsForm:j_idt106")).sendKeys("test message");
driver.findElement(By.id("contactUsForm:j_idt108")).click();
Thread.sleep(8000);
/* driver.findElement(By.id("nextQuote")).click();
assertEquals("LEARN MORE", driver.findElement(By.linkText("LEARN MORE")).getText());
driver.findElement(By.id("nextQuote")).click();
assertEquals("READ MORE", driver.findElement(By.xpath("(//a[contains(text(),'READ MORE')])[6]")).getText());
driver.findElement(By.id("nextQuote")).click();
assertEquals("Legal Matters", driver.findElement(By.linkText("Legal Matters")).getText());
driver.findElement(By.id("nextQuote")).click();
driver.findElement(By.id("nextQuote")).click();*/
	/////ALL LINKS//////*/

   driver.findElement(By.id("contactBasicInfoForm:contactBasicInfoEditBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("contactBasicInfoForm:contactBasicInfoCancelBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("contactBasicInfoForm:contactBasicInfoEditBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("contactBasicInfoForm:homeNumberInput:homeNumberInput")).clear();
   driver.findElement(By.id("contactBasicInfoForm:homeNumberInput:homeNumberInput")).sendKeys("");
   driver.findElement(By.name("contactBasicInfoForm:j_idt123")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt123")).sendKeys("");
   driver.findElement(By.name("contactBasicInfoForm:j_idt127")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt127")).sendKeys("");
   driver.findElement(By.name("contactBasicInfoForm:j_idt131")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt131")).sendKeys("");
   new Select(driver.findElement(By.id("contactBasicInfoForm:j_idt136"))).selectByVisibleText("---United States---");
   driver.findElement(By.name("contactBasicInfoForm:j_idt155")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt155")).sendKeys("");
   driver.findElement(By.name("contactBasicInfoForm:j_idt160")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt160")).sendKeys("");
   driver.findElement(By.id("contactBasicInfoForm:contactBasicInfoSaveBtn")).click();
   Thread.sleep(4000);
   assertEquals("Save failed", driver.findElement(By.cssSelector("h5.text-bold.text-center")).getText());
   assertEquals("Phone Number cannot be empty", driver.findElement(By.xpath("//span[@id='contactBasicInfoForm:contactBasicInfoPanel']/div/div[1]/div[1]/div[4]/div[2]/div[1]/h6")).getText());
   assertEquals("Line 1 cannot be empty", driver.findElement(By.xpath("//div[@id='homeAddressPanel']/div[1]/div[2]/div[1]/h6")).getText());
   assertEquals("City cannot be empty", driver.findElement(By.xpath("//div[@id='homeAddressPanel']/div[3]/div[2]/div/h6")).getText());
   assertEquals("Select State / Province from list", driver.findElement(By.xpath("//span[@id='contactBasicInfoForm:stateFieldPanel']/div[2]/div/h6")).getText());
   assertEquals("Zip / Postal Code cannot be empty", driver.findElement(By.xpath("//span[@id='contactBasicInfoForm:zipTextFieldPanel']/div/h6")).getText());
  Thread.sleep(4000);
  driver.findElement(By.id("contactBasicInfoForm:homeNumberInput:homeNumberInput")).clear();
  driver.findElement(By.cssSelector("div.flag.us")).click();
  driver.findElement(By.id("contactBasicInfoForm:homeNumberInput:homeNumberInput")).sendKeys("77-22-22 22.22");
   driver.findElement(By.name("contactBasicInfoForm:j_idt123")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt123")).sendKeys("address line 1 update");
   driver.findElement(By.name("contactBasicInfoForm:j_idt127")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt127")).sendKeys("address line 2 update");
   driver.findElement(By.name("contactBasicInfoForm:j_idt131")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt131")).sendKeys("Las Vegas");
   new Select(driver.findElement(By.id("contactBasicInfoForm:j_idt136"))).selectByVisibleText("New Hampshire");
   driver.findElement(By.name("contactBasicInfoForm:j_idt131")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt131")).sendKeys("Las Vegas");
   driver.findElement(By.name("contactBasicInfoForm:j_idt155")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt155")).sendKeys("89101");
   driver.findElement(By.name("contactBasicInfoForm:j_idt160")).clear();
   driver.findElement(By.name("contactBasicInfoForm:j_idt160")).sendKeys("secondary@email.com");
   driver.findElement(By.id("contactBasicInfoForm:mobileNumberInput:mobileNumberInput")).clear();
   driver.findElement(By.cssSelector("div.flag.us")).click();
   driver.findElement(By.id("contactBasicInfoForm:mobileNumberInput:mobileNumberInput")).sendKeys("77-22-22 22.22");
   driver.findElement(By.id("contactBasicInfoForm:businessNumberInput:businessNumberInput")).clear();
   driver.findElement(By.cssSelector("div.flag.us")).click();
   driver.findElement(By.id("contactBasicInfoForm:businessNumberInput:businessNumberInput")).sendKeys("87788799-887");
   driver.findElement(By.id("contactBasicInfoForm:satelliteNumberInput:satelliteNumberInput")).clear();
   driver.findElement(By.cssSelector("div.flag.us")).click();
   driver.findElement(By.id("contactBasicInfoForm:satelliteNumberInput:satelliteNumberInput")).sendKeys("87778-8799777");
   driver.findElement(By.id("contactBasicInfoForm:contactBasicInfoSaveBtn")).click();
   Thread.sleep(7000);
   
  /* driver.findElement(By.id("contactBasicInfoForm:contactBasicInfoEditBtn")).click();
   driver.findElement(By.id("contactBasicInfoForm:mobileNumberInput:mobileNumberInput")).clear();
   driver.findElement(By.cssSelector("div.flag.us")).click();
   driver.findElement(By.id("contactBasicInfoForm:mobileNumberInput:mobileNumberInput")).sendKeys("invalid phone");
   driver.findElement(By.id("contactBasicInfoForm:businessNumberInput:businessNumberInput")).clear();
   driver.findElement(By.cssSelector("div.flag.us")).click();
   driver.findElement(By.id("contactBasicInfoForm:businessNumberInput:businessNumberInput")).sendKeys("invalid phone");
   driver.findElement(By.id("contactBasicInfoForm:satelliteNumberInput:satelliteNumberInput")).clear();
   driver.findElement(By.cssSelector("div.flag.us")).click();
   driver.findElement(By.id("contactBasicInfoForm:satelliteNumberInput:satelliteNumberInput")).sendKeys("invalid phone");
   driver.findElement(By.id("contactBasicInfoForm:contactBasicInfoSaveBtn")).click();
   Thread.sleep(5000);
   assertEquals("Only digit, spaces, hyphens and periods are allowed.", driver.findElement(By.cssSelector("h6.errormessage.margin-zero")).getText());
   assertEquals("Only digit, spaces, hyphens and periods are allowed.", driver.findElement(By.xpath("//span[@id='contactBasicInfoForm:contactBasicInfoPanel']/div/div[2]/div[2]/div[3]/div[2]/div/h6")).getText());
   assertEquals("Only digit, spaces, hyphens and periods are allowed.", driver.findElement(By.xpath("//span[@id='contactBasicInfoForm:contactBasicInfoPanel']/div/div[2]/div[2]/div[4]/div[2]/div/h6")).getText());
  */
   System.out.println("Primary member info section updated and validated!");
   
   driver.findElement(By.id("emergencyContactForm:emergencyContactInfoEditBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("emergencyContactForm:emergencyContactInfoCancelBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("emergencyContactForm:emergencyContactInfoEditBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.name("emergencyContactForm:j_idt292")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt292")).sendKeys("123");
   driver.findElement(By.name("emergencyContactForm:j_idt296")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt296")).sendKeys("123");
   driver.findElement(By.name("emergencyContactForm:j_idt300")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt300")).sendKeys("123");
   driver.findElement(By.name("emergencyContactForm:j_idt304")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt304")).sendKeys("1+_)(*&^%$#@!23");
   driver.findElement(By.id("emergencyContactForm:emegencyHomeNumberInput:emegencyHomeNumberInput")).clear();
   driver.findElement(By.cssSelector("div.flag.us")).click();
   driver.findElement(By.id("emergencyContactForm:emegencyHomeNumberInput:emegencyHomeNumberInput")).sendKeys("123");
   driver.findElement(By.id("emergencyContactForm:emegencyMobileNumberInput:emegencyMobileNumberInput")).clear();
   driver.findElement(By.cssSelector("div.flag.us")).click();
   driver.findElement(By.id("emergencyContactForm:emegencyMobileNumberInput:emegencyMobileNumberInput")).sendKeys("123");
   driver.findElement(By.id("emergencyContactForm:emergencyContactInfoSaveBtn")).click();
   Thread.sleep(4000);
   assertEquals("First Name should contain at least one alphabet", driver.findElement(By.cssSelector("h6.errormessage.margin-zero")).getText());
   assertEquals("Last Name should contain at least one alphabet", driver.findElement(By.xpath("//span[@id='emergencyContactForm:emergencyContactInfoPanel']/div/div[2]/div[2]/h6")).getText());
   assertEquals("Email is not Valid.", driver.findElement(By.xpath("//span[@id='emergencyContactForm:emergencyContactInfoPanel']/div[2]/div/div[2]/h6")).getText());
  Thread.sleep(4000);
   driver.findElement(By.name("emergencyContactForm:j_idt292")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt292")).sendKeys("8(*&^%$#@!23766!@#");
   driver.findElement(By.name("emergencyContactForm:j_idt296")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt296")).sendKeys("123(*&^%$#@!23!@#");
   driver.findElement(By.name("emergencyContactForm:j_idt300")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt300")).sendKeys("!@##(*&^%$#@!23$123");
   driver.findElement(By.name("emergencyContactForm:j_idt304")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt304")).sendKeys("1+_)(*&^%$#@!23");
   driver.findElement(By.id("emergencyContactForm:emergencyContactInfoSaveBtn")).click();
   Thread.sleep(4000);
   assertEquals("First Name contains invalid character(s)", driver.findElement(By.cssSelector("h6.errormessage.margin-zero")).getText());
   assertEquals("Last Name contains invalid character(s)", driver.findElement(By.xpath("//span[@id='emergencyContactForm:emergencyContactInfoPanel']/div/div[2]/div[2]/h6")).getText());

   driver.findElement(By.name("emergencyContactForm:j_idt292")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt292")).sendKeys("Ammad");
   driver.findElement(By.name("emergencyContactForm:j_idt296")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt296")).sendKeys("Aslam");
   driver.findElement(By.name("emergencyContactForm:j_idt300")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt300")).sendKeys("Brother");
   driver.findElement(By.name("emergencyContactForm:j_idt304")).clear();
   driver.findElement(By.name("emergencyContactForm:j_idt304")).sendKeys("aaslam@globalrescue.com");
   driver.findElement(By.id("emergencyContactForm:emegencyHomeNumberInput:emegencyHomeNumberInput")).clear();
   driver.findElement(By.cssSelector("div.flag.us")).click();
   driver.findElement(By.id("emergencyContactForm:emegencyHomeNumberInput:emegencyHomeNumberInput")).sendKeys("8877-8877776");
   driver.findElement(By.id("emergencyContactForm:emegencyMobileNumberInput:emegencyMobileNumberInput")).clear();
   driver.findElement(By.cssSelector("div.flag.us")).click();
   driver.findElement(By.id("emergencyContactForm:emegencyMobileNumberInput:emegencyMobileNumberInput")).sendKeys("(998823417-9987");
   driver.findElement(By.id("emergencyContactForm:emergencyContactInfoSaveBtn")).click();
   Thread.sleep(4000);
   System.out.println("Emergency Contact section updated and validated!");
   
   driver.findElement(By.cssSelector("#medicalHistory > a.glyphicon.padding-zero > span")).click();
   Thread.sleep(3000);
   driver.findElement(By.id("medicalHistoryContactForm:medicalHistoryInfoEditBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("medicalHistoryContactForm:medicalHistoryInfoCancelBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("medicalHistoryContactForm:medicalHistoryInfoEditBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("medicalHistoryContactForm:heightFeetField")).clear();
   driver.findElement(By.id("medicalHistoryContactForm:heightFeetField")).sendKeys("55");
   driver.findElement(By.id("medicalHistoryContactForm:heightInchesField")).clear();
   driver.findElement(By.id("medicalHistoryContactForm:heightInchesField")).sendKeys("55");
   driver.findElement(By.id("medicalHistoryContactForm:weightPoundField")).clear();
   driver.findElement(By.id("medicalHistoryContactForm:weightPoundField")).sendKeys("9900");
   driver.findElement(By.id("medicalHistoryContactForm:medicalHistoryInfoSaveBtn")).click();
   Thread.sleep(4000);
   assertEquals("Save failed", driver.findElement(By.cssSelector("h5.text-bold.text-center")).getText());
   assertEquals("Value of Feet cannot be larger than 10", driver.findElement(By.cssSelector("h6.errormessage.margin-zero")).getText());
   assertEquals("Value of Inches cannot be larger than 11", driver.findElement(By.xpath("//span[@id='medicalHistoryContactForm:medicalHistoryInfoPanel']/div/div/div[2]/div[3]/h6")).getText());
   assertEquals("Value of Weight cannot be larger than 1000", driver.findElement(By.xpath("//span[@id='medicalHistoryContactForm:medicalHistoryInfoPanel']/div/div[2]/div[2]/div[2]/h6")).getText());
   driver.findElement(By.id("medicalHistoryContactForm:heightFeetField")).clear();
   driver.findElement(By.id("medicalHistoryContactForm:heightFeetField")).sendKeys("6");
   driver.findElement(By.id("medicalHistoryContactForm:heightInchesField")).clear();
   driver.findElement(By.id("medicalHistoryContactForm:heightInchesField")).sendKeys("6");
   driver.findElement(By.id("medicalHistoryContactForm:weightPoundField")).clear();
   driver.findElement(By.id("medicalHistoryContactForm:weightPoundField")).sendKeys("125");
   driver.findElement(By.id("medicalHistoryContactForm:j_idt342:0")).click();
   driver.findElement(By.id("medicalHistoryContactForm:j_idt350:2")).click();
   driver.findElement(By.id("medicalHistoryContactForm:j_idt358:1")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("medicalHistoryContactForm:anesthesiaDetailsField")).clear();
   driver.findElement(By.id("medicalHistoryContactForm:anesthesiaDetailsField")).sendKeys("Obviously no we are just testing your health");
   driver.findElement(By.id("medicalHistoryContactForm:j_idt366:2")).click();
   driver.findElement(By.id("medicalHistoryContactForm:j_idt374:1")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("medicalHistoryContactForm:anythingElseDetailsField")).clear();
   driver.findElement(By.id("medicalHistoryContactForm:anythingElseDetailsField")).sendKeys("Stay stable and healthy GRCOM!");
   driver.findElement(By.name("medicalHistoryContactForm:j_idt382")).click();
   driver.findElement(By.name("medicalHistoryContactForm:j_idt384")).click();
   driver.findElement(By.name("medicalHistoryContactForm:j_idt386")).click();
   driver.findElement(By.name("medicalHistoryContactForm:j_idt388")).click();
   driver.findElement(By.name("medicalHistoryContactForm:j_idt390")).click();
   driver.findElement(By.name("medicalHistoryContactForm:j_idt392")).click();
   driver.findElement(By.name("medicalHistoryContactForm:j_idt394")).click();
   driver.findElement(By.name("medicalHistoryContactForm:j_idt396")).click();
   //driver.findElement(By.id("medicalHistoryContactForm:j_idt398")).click();
   //Thread.sleep(4000);
  // driver.findElement(By.id("medicalHistoryContactForm:otherIllnessDetailsField")).clear();
  // driver.findElement(By.id("medicalHistoryContactForm:otherIllnessDetailsField")).sendKeys("yes!!!");
   driver.findElement(By.id("medicalHistoryContactForm:j_idt403:0")).click();
   driver.findElement(By.xpath("//table[@id='medicalHistoryContactForm:j_idt403']/tbody/tr/td/label")).click();
   driver.findElement(By.id("medicalHistoryContactForm:j_idt411:2")).click();
   driver.findElement(By.id("medicalHistoryContactForm:medicalHistoryInfoSaveBtn")).click();
   Thread.sleep(4000);
   System.out.println("Medical History Section has been updated and validated!");
   
   driver.findElement(By.cssSelector("#creditCard > a.glyphicon.padding-zero > span")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("creditCardForm:creditCardInfoEditBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("creditCardForm:creditCardInfoCancelBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("creditCardForm:creditCardInfoEditBtn")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("creditCardForm:ccFirstNameTxtField")).clear();
   driver.findElement(By.id("creditCardForm:ccFirstNameTxtField")).sendKeys("");
   driver.findElement(By.id("creditCardForm:ccLastNameTxtField")).clear();
   driver.findElement(By.id("creditCardForm:ccLastNameTxtField")).sendKeys("");
   driver.findElement(By.id("creditCardForm:ccNumberTxtField")).clear();
   driver.findElement(By.id("creditCardForm:ccNumberTxtField")).sendKeys("");
   new Select(driver.findElement(By.name("creditCardForm:j_idt443"))).selectByVisibleText("Month");
   new Select(driver.findElement(By.name("creditCardForm:j_idt446"))).selectByVisibleText("Year");
   driver.findElement(By.id("creditCardForm:billingAddressLine1TxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressLine1TxtField")).sendKeys("");
   driver.findElement(By.id("creditCardForm:billingAddressCityTxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressCityTxtField")).sendKeys("");
   driver.findElement(By.id("creditCardForm:billingAddressZipTxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressZipTxtField")).sendKeys("");
   driver.findElement(By.id("creditCardForm:creditCardInfoSaveBtn")).click();
   Thread.sleep(5000);
   assertEquals("Save failed", driver.findElement(By.cssSelector("h5.text-bold.text-center")).getText());
   assertEquals("First Name cannot be empty", driver.findElement(By.cssSelector("h6.errormessage.margin-zero")).getText());
   assertEquals("Last Name cannot be empty", driver.findElement(By.xpath("//span[@id='creditCardForm:creditCardInfoPanel']/div/div/div/div[2]/div[2]/h6")).getText());
   assertEquals("Credit Card Number cannot be empty", driver.findElement(By.cssSelector("div.col-sm-11.col-xs-12 > h6.errormessage.margin-zero")).getText());
   assertEquals("Invalid Expiry Date", driver.findElement(By.xpath("//span[@id='creditCardForm:creditCardInfoPanel']/div/div/div[3]/div[2]/h6")).getText());
   assertEquals("CVV cannot be empty", driver.findElement(By.cssSelector("div.col-xs-8.padding-zero > h6.errormessage.margin-zero")).getText());
   assertEquals("Line 1 cannot be empty", driver.findElement(By.cssSelector("div.col-sm-8.col-xs-12 > h6.errormessage.margin-zero")).getText());
   assertEquals("City cannot be empty", driver.findElement(By.xpath("//span[@id='creditCardForm:billingAddressPanel']/div[4]/div[2]/h6")).getText());
   assertEquals("Zip / Postal Code cannot be empty", driver.findElement(By.xpath("//span[@id='creditCardForm:billingZipTextFieldPanel']/h6")).getText());
   driver.findElement(By.id("creditCardForm:ccFirstNameTxtField")).clear();
   driver.findElement(By.id("creditCardForm:ccFirstNameTxtField")).sendKeys("@#$%%");
   driver.findElement(By.id("creditCardForm:ccLastNameTxtField")).clear();
   driver.findElement(By.id("creditCardForm:ccLastNameTxtField")).sendKeys("#$%^^");
   driver.findElement(By.id("creditCardForm:ccNumberTxtField")).clear();
   driver.findElement(By.id("creditCardForm:ccNumberTxtField")).sendKeys("34455");
   new Select(driver.findElement(By.name("creditCardForm:j_idt443"))).selectByVisibleText("Jan");
   new Select(driver.findElement(By.name("creditCardForm:j_idt446"))).selectByVisibleText("2015");
   driver.findElement(By.id("creditCardForm:cvvTxtField")).clear();
   driver.findElement(By.id("creditCardForm:cvvTxtField")).sendKeys("2");
   driver.findElement(By.id("creditCardForm:billingAddressLine1TxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressLine1TxtField")).sendKeys("asasas");
   driver.findElement(By.id("creditCardForm:billingAddressLine2TxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressLine2TxtField")).sendKeys("asas");
   driver.findElement(By.id("creditCardForm:billingAddressCityTxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressCityTxtField")).sendKeys("asas");
   driver.findElement(By.id("creditCardForm:billingAddressZipTxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressZipTxtField")).sendKeys("asas");
   driver.findElement(By.id("creditCardForm:creditCardInfoSaveBtn")).click();
   Thread.sleep(5000);
   assertEquals("First Name contains invalid character(s)", driver.findElement(By.cssSelector("h6.errormessage.margin-zero")).getText());
   assertEquals("Last Name contains invalid character(s)", driver.findElement(By.xpath("//span[@id='creditCardForm:creditCardInfoPanel']/div/div/div/div[2]/div[2]/h6")).getText());
   assertEquals("Invalid Credit Card Number", driver.findElement(By.cssSelector("div.col-sm-11.col-xs-12 > h6.errormessage.margin-zero")).getText());
   assertEquals("Expiration Date cannot be past date", driver.findElement(By.xpath("//span[@id='creditCardForm:creditCardInfoPanel']/div/div/div[3]/div[2]/h6")).getText());
   assertEquals("CVV cannot be less than 3 digits", driver.findElement(By.cssSelector("div.col-xs-8.padding-zero > h6.errormessage.margin-zero")).getText());
   driver.findElement(By.id("creditCardForm:ccNumberTxtField")).clear();
   driver.findElement(By.id("creditCardForm:ccNumberTxtField")).sendKeys("444444444444444444444444444444444444");
   driver.findElement(By.id("creditCardForm:cvvTxtField")).clear();
   driver.findElement(By.id("creditCardForm:cvvTxtField")).sendKeys("2444");
   driver.findElement(By.id("creditCardForm:creditCardInfoSaveBtn")).click();
   Thread.sleep(5000);
   assertEquals("Credit Card Number cannot be longer than 16 characters", driver.findElement(By.cssSelector("div.col-sm-11.col-xs-12 > h6.errormessage.margin-zero")).getText());
   driver.findElement(By.id("creditCardForm:ccFirstNameTxtField")).clear();
   driver.findElement(By.id("creditCardForm:ccFirstNameTxtField")).sendKeys("test");
   driver.findElement(By.id("creditCardForm:ccLastNameTxtField")).clear();
   driver.findElement(By.id("creditCardForm:ccLastNameTxtField")).sendKeys("cutomer");
   driver.findElement(By.id("creditCardForm:ccNumberTxtField")).clear();
   driver.findElement(By.id("creditCardForm:ccNumberTxtField")).sendKeys("4111111111111111");
   new Select(driver.findElement(By.name("creditCardForm:j_idt446"))).selectByVisibleText("2025");
   driver.findElement(By.id("creditCardForm:billingAddressLine1TxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressLine1TxtField")).sendKeys("address 1");
   driver.findElement(By.id("creditCardForm:billingAddressLine2TxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressLine2TxtField")).sendKeys("address 2");
   driver.findElement(By.id("creditCardForm:billingAddressCityTxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressCityTxtField")).sendKeys("las vegas");
   driver.findElement(By.id("creditCardForm:billingAddressZipTxtField")).clear();
   driver.findElement(By.id("creditCardForm:billingAddressZipTxtField")).sendKeys("89101");
   driver.findElement(By.cssSelector("h4.margin-zero.margin-top-quarter-em")).click();
   Thread.sleep(4000);
   assertEquals("For Visa and Mastercard users, the CVV is the three digit security code located on the back of your card.", driver.findElement(By.xpath("//div[@id='cvvInfoModal']/div/div/div[2]/div/div/h5")).getText());
   assertEquals("For American Express users, the CVV is the four digit security code located on the front of your card.", driver.findElement(By.xpath("//div[@id='cvvInfoModal']/div/div/div[2]/div/div/h5[2]")).getText());
   driver.findElement(By.xpath("(//button[@type='button'])[6]")).click();
   Thread.sleep(4000);
   driver.findElement(By.id("creditCardForm:creditCardInfoSaveBtn")).click();
   Thread.sleep(10000);
   System.out.println("Credit Card has been updated and validation has been checked!");
   driver.findElement(By.cssSelector("a.text-red.border-right-gray-dashed > h6.margin-zero")).click();
   driver.findElement(By.cssSelector("a.text-red.border-right-gray-dashed > h6.margin-zero")).click();
   Thread.sleep(10000);
   System.out.println("User has been Logged Out!");
   System.out.println("***Thank You***");
}
  
  

private void assertTrue(Object elementPresent) {
	// TODO Auto-generated method stub
	
}

private Object isElementPresent(By id) {
	// TODO Auto-generated method stub
	return null;
}
}
